<?php

/**
 * BaseJobeetRoutes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $price
 * @property integer $address_id_a
 * @property integer $address_id_b
 * 
 * @method decimal      getPrice()        Returns the current record's "price" value
 * @method integer      getAddressIdA()   Returns the current record's "address_id_a" value
 * @method integer      getAddressIdB()   Returns the current record's "address_id_b" value
 * @method JobeetRoutes setPrice()        Sets the current record's "price" value
 * @method JobeetRoutes setAddressIdA()   Sets the current record's "address_id_a" value
 * @method JobeetRoutes setAddressIdB()   Sets the current record's "address_id_b" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseJobeetRoutes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobeet_routes');
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('address_id_a', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address_id_b', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}