<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/07/06 11:56:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => '1',
  'name' => 'doctrine',
)),);
