<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/07/07 17:26:00
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinegenerateadmintask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinedqltask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedeletemodelfilestask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinebuildfilterstask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebasetask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebuildsqltask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildmodeltask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegeneratemigrationtask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinedatadumptask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinegeneratemoduletask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinecreatemodeltables' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinebuildschematask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildtask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinecleanmodelfilestask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinemigratetask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinedataloadtask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrineconfiguredatabasetask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinebuilddbtask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinedropdbtask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrineinsertsqltask' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sftesterdoctrine' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfwebdebugpaneldoctrine' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrineconnectionprofiler' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionlistener' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineexception' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfvalidatordoctrineunique' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfdoctrinepager' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinecli' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'swift_doctrinespool' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinerecord' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfformdoctrine' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrineroute' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrinecolumn' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinegenerator' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformfiltergenerator' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfwidgetformdoctrinechoice' => dirname(__FILE__).'/../../../../lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basejobeetroutesformfilter' => dirname(__FILE__).'/../../../../lib/filter/doctrine/base/BaseJobeetRoutesFormFilter.class.php',
  'basejobeetaddressesformfilter' => dirname(__FILE__).'/../../../../lib/filter/doctrine/base/BaseJobeetAddressesFormFilter.class.php',
  'baseformfilterdoctrine' => dirname(__FILE__).'/../../../../lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'jobeetroutesformfilter' => dirname(__FILE__).'/../../../../lib/filter/doctrine/JobeetRoutesFormFilter.class.php',
  'jobeetaddressesformfilter' => dirname(__FILE__).'/../../../../lib/filter/doctrine/JobeetAddressesFormFilter.class.php',
  'jobeetroutesform' => dirname(__FILE__).'/../../../../lib/form/doctrine/JobeetRoutesForm.class.php',
  'jobeetaddressesform' => dirname(__FILE__).'/../../../../lib/form/doctrine/JobeetAddressesForm.class.php',
  'baseformdoctrine' => dirname(__FILE__).'/../../../../lib/form/doctrine/BaseFormDoctrine.class.php',
  'basejobeetroutesform' => dirname(__FILE__).'/../../../../lib/form/doctrine/base/BaseJobeetRoutesForm.class.php',
  'basejobeetaddressesform' => dirname(__FILE__).'/../../../../lib/form/doctrine/base/BaseJobeetAddressesForm.class.php',
  'baseform' => dirname(__FILE__).'/../../../../lib/form/BaseForm.class.php',

  // project_model
  'jobeetaddresses' => dirname(__FILE__).'/../../../../lib/model/doctrine/JobeetAddresses.class.php',
  'basejobeetroutes' => dirname(__FILE__).'/../../../../lib/model/doctrine/base/BaseJobeetRoutes.class.php',
  'basejobeetaddresses' => dirname(__FILE__).'/../../../../lib/model/doctrine/base/BaseJobeetAddresses.class.php',
  'jobeetaddressestable' => dirname(__FILE__).'/../../../../lib/model/doctrine/JobeetAddressesTable.class.php',
  'jobeetroutestable' => dirname(__FILE__).'/../../../../lib/model/doctrine/JobeetRoutesTable.class.php',
  'jobeetroutes' => dirname(__FILE__).'/../../../../lib/model/doctrine/JobeetRoutes.class.php',

  // application
  'myuser' => dirname(__FILE__).'/../../../../apps/frontend/lib/myUser.class.php',

  // modules
);
